version: '3'
services:
auth:
container_name: auth
image: authelia/authelia:latest
expose:
- 9091
volumes:
- /opt/appdata/authelia:/config
labels:
traefik.enable: true
traefik.http.routers.authelia.entryPoints: https
networks:
- proxy
restart: unless-stopped
depends_on:
- redis
- mariadb
redis:
container_name: redis
image: bitnami/redis:latest
expose:
- 6379
volumes:
- /opt/appdata/redis:/bitnami/
environment:
REDIS_PASSWORD: "YOUR_REDIS_PASSWORD"
networks:
- proxy
restart: unless-stopped
mariadb:
container_name: mariadb
image: linuxserver/mariadb:latest
expose:
- 3306
volumes:
- /opt/appdata/mariadb:/config
environment:
MYSQL_ROOT_PASSWORD: "YOUR_MYSQL_ROOT_PASSWORD"
MYSQL_ROOT_USER: root
MYSQL_DATABASE: authelia
MYSQL_USER: authelia
MYSQL_PASSWORD: "YOUR_MYSQL_USER_PASSWORD"
networks:
- proxy
restart: unless-stopped
networks:
proxy:



# services:
#   vaultwarden:
#     image: vaultwarden/server:latest
#     container_name: vaultwarden
#     restart: always
#     volumes:
#       - ./vw-data:/data
#     environment:
#       - WEBSOCKET_ENABLED=true
#     ports:
#       - "8080:80"


# environment:
    #   - TZ=your_timezone # replace with your actual timezone
    # environment:
    #   - TZ=Asia/Kolkata # replace with your actual timezone
    #   - AUTHENTICATION_BACKEND=file # specify the authentication backend
    #   - DEFAULT_POLICY=two_factor # set default_policy to two_factor
    #   # - STORAGE=file # specify the storage backend
    #   # - NOTIFIER=smtp # specify the notifier backend
    #   # - SMTP_HOST=smtp.example.com # replace with your SMTP host
    #   # - SMTP_PORT=587 # replace with your SMTP port
    #   # - SMTP_USERNAME=example # replace with your SMTP username
    #   # - SMTP_PASSWORD=secret # replace with your SMTP password
    #   # - SMTP_FROM_ADDRESS=authelia@example.com # replace with your SMTP from address
    #   # - JWT_SECRET=mysecret # replace with your JWT secret
    # ports:
    #   - 8081:8080 # adjust the port to your preference


    # services:
#   vaultwarden:
#     image: vaultwarden/server:latest
#     container_name: vaultwarden
#     restart: always
#     volumes:
#       - ./vw-data:/data
#     environment:
#       - WEBSOCKET_ENABLED=true
#     ports:
#       - "8080:80"